apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: ecommerce
  labels:
    app: order-management
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
        tier: backend
    spec:
      containers:
      - name: order-management
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "order-management"
        - name: PRODUCT_CATALOG_URL
          value: "http://product-catalog:8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: order-management-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-management-config
  namespace: ecommerce
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api/health {
            return 200 '{"status":"ok","service":"order-management","healthy":true}';
            add_header Content-Type application/json;
        }
        
        location /api/orders {
            if ($request_method = POST) {
                return 201 '{"orderId":"ORD-'$request_id'","status":"confirmed","message":"Order received successfully"}';
            }
            return 200 '{"orders":[{"id":"ORD-001","total":599.99,"status":"shipped","items":2},{"id":"ORD-002","total":299.99,"status":"processing","items":1}],"service":"order-management"}';
            add_header Content-Type application/json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: order-management
  namespace: ecommerce
  labels:
    app: order-management
spec:
  type: ClusterIP
  selector:
    app: order-management
  ports:
  - port: 8080
    targetPort: 80
    name: http