apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-management
  namespace: ecommerce
  labels:
    app: profile-management
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
  template:
    metadata:
      labels:
        app: profile-management
        tier: backend
    spec:
      containers:
      - name: profile-management
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: profile-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
  namespace: ecommerce
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api/health {
            return 200 '{"status":"ok","service":"profile-management"}';
            add_header Content-Type application/json;
        }
        
        location /api/profile {
            return 200 '{"user":"demo","email":"demo@example.com","service":"profile-management"}';
            add_header Content-Type application/json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: profile-management
  namespace: ecommerce
  labels:
    app: profile-management
spec:
  type: ClusterIP
  selector:
    app: profile-management
  ports:
  - port: 8080
    targetPort: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-handling
  namespace: ecommerce
  labels:
    app: shipping-handling
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-handling
  template:
    metadata:
      labels:
        app: shipping-handling
        tier: backend
    spec:
      containers:
      - name: shipping-handling
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: shipping-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: ecommerce
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api/health {
            return 200 '{"status":"ok","service":"shipping-handling"}';
            add_header Content-Type application/json;
        }
        
        location /api/shipping {
            return 200 '{"status":"available","methods":["standard","express"],"service":"shipping-handling"}';
            add_header Content-Type application/json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-handling
  namespace: ecommerce
  labels:
    app: shipping-handling
spec:
  type: ClusterIP
  selector:
    app: shipping-handling
  ports:
  - port: 8080
    targetPort: 80
    name: http