apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-support
  namespace: ecommerce
  labels:
    app: contact-support
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-support
  template:
    metadata:
      labels:
        app: contact-support
        tier: backend
    spec:
      containers:
      - name: contact-support
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: support-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-config
  namespace: ecommerce
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api/health {
            return 200 '{"status":"ok","service":"contact-support"}';
            add_header Content-Type application/json;
        }
        
        location /api/support {
            return 200 '{"contact":"support@ecommerce.com","hours":"24/7","service":"contact-support"}';
            add_header Content-Type application/json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: contact-support
  namespace: ecommerce
  labels:
    app: contact-support
spec:
  type: ClusterIP
  selector:
    app: contact-support
  ports:
  - port: 8080
    targetPort: 80
    name: http